global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "django"
    static_configs:
      - targets: ["django:8000"]
    metrics_path: /metrics
    scheme: http
    # relabel_configs:
    #   - source_labels: [__address__]
    #     regex: "([^:]+):\\d+"
    #     target_label: instance
