global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: django
    metrics_path: '/prometheus/metrics'
    static_configs:
      - targets:
          - 172.17.0.1:8000
